version: "2.4"
services:
  app:
    image: node:buster-slim
    container_name: netlify-dns
    env_file:
      - compose-variables.env
    restart: unless-stopped
    volumes:
      - ./netlify-dns.js:/app/netlify-dns.js
      - ./package.json:/app/package.json
    command: bash -c 'cd app && npm i && node ./netlify-dns.js'